// DO NOT EDIT
// Generated by JFlex 1.9.1 http://jflex.de/
// source: src/lexer.jflex

import java_cup.runtime.Symbol;




@SuppressWarnings("fallthrough")
class Lexer implements java_cup.runtime.Scanner {

  /** This character denotes the end of file. */
  public static final int YYEOF = -1;

  /** Initial size of the lookahead buffer. */
  private static final int ZZ_BUFFERSIZE = 16384;

  // Lexical states.
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = {
     0, 0
  };

  /**
   * Top-level table for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_TOP = zzUnpackcmap_top();

  private static final String ZZ_CMAP_TOP_PACKED_0 =
    "\1\0\37\u0100\1\u0200\267\u0100\10\u0300\u1020\u0100";

  private static int [] zzUnpackcmap_top() {
    int [] result = new int[4352];
    int offset = 0;
    offset = zzUnpackcmap_top(ZZ_CMAP_TOP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_top(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Second-level tables for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_BLOCKS = zzUnpackcmap_blocks();

  private static final String ZZ_CMAP_BLOCKS_PACKED_0 =
    "\11\0\1\1\1\2\2\3\1\4\22\0\1\1\1\0"+
    "\1\5\1\6\1\0\1\7\1\0\1\10\1\11\1\12"+
    "\1\13\1\14\1\15\1\16\1\0\1\17\1\20\11\21"+
    "\1\22\1\23\1\24\1\25\1\26\1\27\1\0\6\30"+
    "\24\31\1\32\1\33\1\34\1\0\1\35\1\0\1\36"+
    "\1\37\1\40\1\41\1\42\1\43\1\31\1\44\1\45"+
    "\1\31\1\46\1\47\1\50\1\51\1\52\1\53\1\31"+
    "\1\54\1\55\1\56\1\57\1\31\1\60\1\61\2\31"+
    "\12\0\1\3\u01a2\0\2\3\326\0\u0100\3";

  private static int [] zzUnpackcmap_blocks() {
    int [] result = new int[1024];
    int offset = 0;
    offset = zzUnpackcmap_blocks(ZZ_CMAP_BLOCKS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_blocks(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /**
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\1\2\1\1\1\3\1\2\1\1\1\4"+
    "\1\5\1\6\1\7\1\10\1\11\1\12\1\13\1\14"+
    "\1\15\1\16\1\17\1\20\1\21\1\22\1\23\17\21"+
    "\1\0\1\24\3\0\1\25\1\26\1\27\1\30\12\21"+
    "\1\31\6\21\1\32\4\21\1\33\1\0\1\34\3\21"+
    "\1\35\1\21\1\36\2\21\1\37\1\21\1\40\1\21"+
    "\1\41\1\42\1\43\1\44\1\45\4\21\1\0\1\46"+
    "\1\47\1\50\1\51\1\21\1\52\1\21\1\53\1\54"+
    "\1\55\1\21\1\56\1\57\1\60\1\61\1\62\1\21"+
    "\1\63";

  private static int [] zzUnpackAction() {
    int [] result = new int[112];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\62\0\144\0\226\0\62\0\310\0\372\0\62"+
    "\0\62\0\62\0\62\0\62\0\62\0\62\0\u012c\0\u015e"+
    "\0\62\0\u0190\0\62\0\u01c2\0\u01f4\0\62\0\62\0\u0226"+
    "\0\u0258\0\u028a\0\u02bc\0\u02ee\0\u0320\0\u0352\0\u0384\0\u03b6"+
    "\0\u03e8\0\u041a\0\u044c\0\u047e\0\u04b0\0\u04e2\0\226\0\62"+
    "\0\u0514\0\u0546\0\u0578\0\62\0\62\0\62\0\62\0\u05aa"+
    "\0\u05dc\0\u060e\0\u0640\0\u0672\0\u06a4\0\u06d6\0\u0708\0\u073a"+
    "\0\u076c\0\u01f4\0\u079e\0\u07d0\0\u0802\0\u0834\0\u0866\0\u0898"+
    "\0\u01f4\0\u08ca\0\u08fc\0\u092e\0\u0960\0\62\0\u0992\0\u01f4"+
    "\0\u09c4\0\u09f6\0\u0a28\0\u01f4\0\u0a5a\0\u01f4\0\u0a8c\0\u0abe"+
    "\0\u01f4\0\u0af0\0\u01f4\0\u0b22\0\u01f4\0\u01f4\0\u0b54\0\u01f4"+
    "\0\u01f4\0\u0b86\0\u0bb8\0\u0bea\0\u0c1c\0\u0c4e\0\u01f4\0\u01f4"+
    "\0\u01f4\0\u01f4\0\u0c80\0\u01f4\0\u0cb2\0\u01f4\0\u01f4\0\u01f4"+
    "\0\u0ce4\0\u01f4\0\u01f4\0\u01f4\0\u01f4\0\u01f4\0\u0d16\0\u01f4";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[112];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length() - 1;
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /**
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpacktrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\2\3\1\0\1\3\1\4\1\5\1\6\1\7"+
    "\1\10\1\11\1\12\1\13\1\14\1\15\1\16\2\17"+
    "\1\20\1\21\1\22\1\23\1\24\1\2\2\25\1\26"+
    "\1\2\1\27\1\2\1\30\1\31\1\32\1\33\1\34"+
    "\1\35\1\36\1\37\1\25\1\40\1\41\1\42\1\43"+
    "\1\25\1\44\1\45\1\46\3\25\63\0\2\3\1\0"+
    "\1\3\55\0\2\47\1\0\1\47\1\0\1\50\25\47"+
    "\1\51\26\47\2\6\1\0\57\6\2\52\1\0\1\52"+
    "\1\0\3\52\1\0\22\52\1\53\26\52\20\0\2\17"+
    "\65\0\1\54\61\0\1\55\1\56\60\0\1\57\54\0"+
    "\2\25\5\0\3\25\3\0\25\25\20\0\2\25\5\0"+
    "\3\25\3\0\14\25\1\60\10\25\20\0\2\25\5\0"+
    "\3\25\3\0\15\25\1\61\7\25\20\0\2\25\5\0"+
    "\3\25\3\0\7\25\1\62\15\25\20\0\2\25\5\0"+
    "\3\25\3\0\5\25\1\63\17\25\20\0\2\25\5\0"+
    "\3\25\3\0\12\25\1\64\1\25\1\65\7\25\1\66"+
    "\20\0\2\25\5\0\3\25\3\0\1\25\1\67\13\25"+
    "\1\70\7\25\20\0\2\25\5\0\3\25\3\0\5\25"+
    "\1\71\17\25\20\0\2\25\5\0\3\25\3\0\6\25"+
    "\1\72\5\25\1\73\10\25\20\0\2\25\5\0\3\25"+
    "\3\0\10\25\1\74\14\25\20\0\2\25\5\0\3\25"+
    "\3\0\15\25\1\75\7\25\20\0\2\25\5\0\3\25"+
    "\3\0\5\25\1\76\2\25\1\77\4\25\1\100\7\25"+
    "\20\0\2\25\5\0\3\25\3\0\17\25\1\101\5\25"+
    "\20\0\2\25\5\0\3\25\3\0\5\25\1\102\17\25"+
    "\20\0\2\25\5\0\3\25\3\0\11\25\1\103\13\25"+
    "\20\0\2\25\5\0\3\25\3\0\1\25\1\104\15\25"+
    "\1\105\5\25\5\0\1\47\2\0\1\47\7\0\1\47"+
    "\12\0\1\47\15\0\1\47\2\0\1\47\1\0\1\47"+
    "\13\0\1\106\56\0\1\52\2\0\1\52\7\0\1\52"+
    "\12\0\1\52\15\0\1\52\2\0\1\52\1\0\1\52"+
    "\2\0\1\107\20\0\2\25\5\0\3\25\3\0\4\25"+
    "\1\110\20\25\20\0\2\25\5\0\3\25\3\0\15\25"+
    "\1\111\7\25\20\0\2\25\5\0\3\25\3\0\1\25"+
    "\1\112\23\25\20\0\2\25\5\0\3\25\3\0\3\25"+
    "\1\113\2\25\1\114\16\25\20\0\2\25\5\0\3\25"+
    "\3\0\20\25\1\115\4\25\20\0\2\25\5\0\3\25"+
    "\3\0\4\25\1\116\20\25\20\0\2\25\5\0\3\25"+
    "\3\0\10\25\1\117\14\25\20\0\2\25\5\0\3\25"+
    "\3\0\12\25\1\120\12\25\20\0\2\25\5\0\3\25"+
    "\3\0\17\25\1\121\5\25\20\0\2\25\5\0\3\25"+
    "\3\0\1\25\1\122\23\25\20\0\2\25\5\0\3\25"+
    "\3\0\21\25\1\123\3\25\20\0\2\25\5\0\3\25"+
    "\3\0\20\25\1\124\4\25\20\0\2\25\5\0\3\25"+
    "\3\0\4\25\1\125\20\25\20\0\2\25\5\0\3\25"+
    "\3\0\23\25\1\126\1\25\20\0\2\25\5\0\3\25"+
    "\3\0\12\25\1\127\12\25\20\0\2\25\5\0\3\25"+
    "\3\0\21\25\1\130\3\25\20\0\2\25\5\0\3\25"+
    "\3\0\6\25\1\131\12\25\1\132\3\25\20\0\2\25"+
    "\5\0\3\25\3\0\10\25\1\133\14\25\20\0\2\25"+
    "\5\0\3\25\3\0\10\25\1\134\14\25\20\0\2\25"+
    "\5\0\3\25\3\0\22\25\1\135\2\25\20\0\2\136"+
    "\6\0\1\136\5\0\6\136\36\0\2\25\5\0\3\25"+
    "\3\0\12\25\1\137\12\25\20\0\2\25\5\0\3\25"+
    "\3\0\17\25\1\140\5\25\20\0\2\25\5\0\3\25"+
    "\3\0\12\25\1\141\12\25\20\0\2\25\5\0\3\25"+
    "\3\0\5\25\1\142\2\25\1\143\14\25\20\0\2\25"+
    "\5\0\3\25\3\0\21\25\1\144\3\25\20\0\2\25"+
    "\5\0\3\25\3\0\20\25\1\145\4\25\20\0\2\25"+
    "\5\0\3\25\3\0\4\25\1\146\20\25\20\0\2\25"+
    "\5\0\3\25\3\0\21\25\1\147\3\25\20\0\2\25"+
    "\5\0\1\150\2\25\3\0\25\25\20\0\2\25\5\0"+
    "\3\25\3\0\22\25\1\151\2\25\20\0\2\25\5\0"+
    "\3\25\3\0\16\25\1\152\6\25\20\0\2\25\5\0"+
    "\3\25\3\0\12\25\1\153\12\25\20\0\2\25\5\0"+
    "\3\25\3\0\5\25\1\154\17\25\20\0\2\52\6\0"+
    "\1\52\5\0\6\52\36\0\2\25\5\0\3\25\3\0"+
    "\6\25\1\155\16\25\20\0\2\25\5\0\3\25\3\0"+
    "\5\25\1\156\17\25\20\0\2\25\5\0\3\25\3\0"+
    "\17\25\1\157\5\25\20\0\2\25\5\0\3\25\3\0"+
    "\14\25\1\160\10\25";

  private static int [] zzUnpacktrans() {
    int [] result = new int[3400];
    int offset = 0;
    offset = zzUnpacktrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpacktrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** Error code for "Unknown internal scanner error". */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  /** Error code for "could not match input". */
  private static final int ZZ_NO_MATCH = 1;
  /** Error code for "pushback value was too large". */
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /**
   * Error messages for {@link #ZZ_UNKNOWN_ERROR}, {@link #ZZ_NO_MATCH}, and
   * {@link #ZZ_PUSHBACK_2BIG} respectively.
   */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state {@code aState}
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\11\2\1\1\11\2\1\7\11\2\1\1\11"+
    "\1\1\1\11\2\1\2\11\17\1\1\0\1\11\3\0"+
    "\4\11\26\1\1\11\1\0\26\1\1\0\22\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[112];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** Input device. */
  private java.io.Reader zzReader;

  /** Current state of the DFA. */
  private int zzState;

  /** Current lexical state. */
  private int zzLexicalState = YYINITIAL;

  /**
   * This buffer contains the current text to be matched and is the source of the {@link #yytext()}
   * string.
   */
  private char zzBuffer[] = new char[Math.min(ZZ_BUFFERSIZE, zzMaxBufferLen())];

  /** Text position at the last accepting state. */
  private int zzMarkedPos;

  /** Current text position in the buffer. */
  private int zzCurrentPos;

  /** Marks the beginning of the {@link #yytext()} string in the buffer. */
  private int zzStartRead;

  /** Marks the last character in the buffer, that has been read from input. */
  private int zzEndRead;

  /**
   * Whether the scanner is at the end of file.
   * @see #yyatEOF
   */
  private boolean zzAtEOF;

  /**
   * The number of occupied positions in {@link #zzBuffer} beyond {@link #zzEndRead}.
   *
   * <p>When a lead/high surrogate has been read from the input stream into the final
   * {@link #zzBuffer} position, this will have a value of 1; otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /** Number of newlines encountered up to the start of the matched text. */
  private int yyline;

  /** Number of characters from the last newline up to the start of the matched text. */
  private int yycolumn;

  /** Number of characters up to the start of the matched text. */
  @SuppressWarnings("unused")
  private long yychar;

  /** Whether the scanner is currently at the beginning of a line. */
  @SuppressWarnings("unused")
  private boolean zzAtBOL = true;

  /** Whether the user-EOF-code has already been executed. */
  private boolean zzEOFDone;

  /* user code: */
        

public static class Token {
        // keywords
        public static final int T_AND = 1;
        public static final int T_BOOL = 2;
        public static final int T_CHAR = 3;
        public static final int T_DECL = 4;
        public static final int T_DEF = 5;
        public static final int T_ELSE = 6;
        public static final int T_ELSIF = 7;
        public static final int T_END = 8;
        public static final int T_EXIT = 9;
        public static final int T_FALSE = 10;
        public static final int T_FOR = 11;
        public static final int T_HEAD = 12;
        public static final int T_IF = 13;
        public static final int T_INT = 14;
        public static final int T_LIST = 15;
        public static final int T_MOD = 16;
        public static final int T_NEW = 17;
        public static final int T_NIL = 18;
        public static final int T_NILQ = 19;   // nil?
        public static final int T_NOT = 20;
        public static final int T_OR = 21;
        public static final int T_REF = 22;
        public static final int T_RETURN = 23;
        public static final int T_SKIP = 24;
        public static final int T_TAIL = 25;
        public static final int T_TRUE = 26;

        // general
        public static final int T_ID = 27;
        public static final int T_NUM = 28;
        public static final int T_STRING = 29;

        // separators
        public static final int T_LPAR = 30;      // (
        public static final int T_RPAR = 31;      // )
        public static final int T_LBRACKET = 32;  // [
        public static final int T_RBRACKET = 33;  // ]
        public static final int T_COMMA = 34;     // ,
        public static final int T_SEMICOLON = 35; // ;
        public static final int T_COLON = 36;     // :
        public static final int T_ASSIGN = 37;    // :=

        // operators
        public static final int T_PLUS = 38;      // +
        public static final int T_MINUS = 39;     // -
        public static final int T_TIMES = 40;     // *
        public static final int T_DIV = 41;       // /
        public static final int T_EQ = 42;        // =
        public static final int T_NEQ = 43;       // <>
        public static final int T_LT = 44;        // <
        public static final int T_GT = 45;        // >
        public static final int T_LE = 46;        // <=
        public static final int T_GE = 47;        // >=
        public static final int T_HASH = 48;      // #
        public static final int T_CHARCONST = 49;
};



  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  Lexer(java.io.Reader in) {
    this.zzReader = in;
  }


  /** Returns the maximum size of the scanner buffer, which limits the size of tokens. */
  private int zzMaxBufferLen() {
    return Integer.MAX_VALUE;
  }

  /**  Whether the scanner buffer can grow to accommodate a larger token. */
  private boolean zzCanGrow() {
    return true;
  }

  /**
   * Translates raw input code points to DFA table row
   */
  private static int zzCMap(int input) {
    int offset = input & 255;
    return offset == input ? ZZ_CMAP_BLOCKS[offset] : ZZ_CMAP_BLOCKS[ZZ_CMAP_TOP[input >> 8] | offset];
  }

  /**
   * Refills the input buffer.
   *
   * @return {@code false} iff there was new input.
   * @exception java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead - zzStartRead);

      /* translate stored positions */
      zzEndRead -= zzStartRead;
      zzCurrentPos -= zzStartRead;
      zzMarkedPos -= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate && zzCanGrow()) {
      /* if not, and it can grow: blow it up */
      char newBuffer[] = new char[Math.min(zzBuffer.length * 2, zzMaxBufferLen())];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      if (requested == 0) {
        throw new java.io.EOFException("Scan buffer limit reached ["+zzBuffer.length+"]");
      }
      else {
        throw new java.io.IOException(
            "Reader returned 0 characters. See JFlex examples/zero-reader for a workaround.");
      }
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
        if (numRead == requested) { // We requested too few chars to encode a full Unicode character
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        } else {                    // There is room in the buffer for at least one more char
          int c = zzReader.read();  // Expecting to read a paired low surrogate char
          if (c == -1) {
            return true;
          } else {
            zzBuffer[zzEndRead++] = (char)c;
          }
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }


  /**
   * Closes the input reader.
   *
   * @throws java.io.IOException if the reader could not be closed.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true; // indicate end of file
    zzEndRead = zzStartRead; // invalidate buffer

    if (zzReader != null) {
      zzReader.close();
    }
  }


  /**
   * Resets the scanner to read from a new input stream.
   *
   * <p>Does not close the old reader.
   *
   * <p>All internal variables are reset, the old input stream <b>cannot</b> be reused (internal
   * buffer is discarded and lost). Lexical state is set to {@code ZZ_INITIAL}.
   *
   * <p>Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader The new input stream.
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzEOFDone = false;
    yyResetPosition();
    zzLexicalState = YYINITIAL;
    int initBufferSize = Math.min(ZZ_BUFFERSIZE, zzMaxBufferLen());
    if (zzBuffer.length > initBufferSize) {
      zzBuffer = new char[initBufferSize];
    }
  }

  /**
   * Resets the input position.
   */
  private final void yyResetPosition() {
      zzAtBOL  = true;
      zzAtEOF  = false;
      zzCurrentPos = 0;
      zzMarkedPos = 0;
      zzStartRead = 0;
      zzEndRead = 0;
      zzFinalHighSurrogate = 0;
      yyline = 0;
      yycolumn = 0;
      yychar = 0L;
  }


  /**
   * Returns whether the scanner has reached the end of the reader it reads from.
   *
   * @return whether the scanner has reached EOF.
   */
  public final boolean yyatEOF() {
    return zzAtEOF;
  }


  /**
   * Returns the current lexical state.
   *
   * @return the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state.
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   *
   * @return the matched text.
   */
  public final String yytext() {
    return new String(zzBuffer, zzStartRead, zzMarkedPos-zzStartRead);
  }


  /**
   * Returns the character at the given position from the matched text.
   *
   * <p>It is equivalent to {@code yytext().charAt(pos)}, but faster.
   *
   * @param position the position of the character to fetch. A value from 0 to {@code yylength()-1}.
   *
   * @return the character at {@code position}.
   */
  public final char yycharat(int position) {
    return zzBuffer[zzStartRead + position];
  }


  /**
   * How many characters were matched.
   *
   * @return the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occurred while scanning.
   *
   * <p>In a well-formed scanner (no or only correct usage of {@code yypushback(int)} and a
   * match-all fallback rule) this method will only be called with things that
   * "Can't Possibly Happen".
   *
   * <p>If this method is called, something is seriously wrong (e.g. a JFlex bug producing a faulty
   * scanner etc.).
   *
   * <p>Usual syntax/scanner level error handling should be done in error fallback rules.
   *
   * @param errorCode the code of the error message to display.
   */
  private static void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    } catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * <p>They will be read again by then next call of the scanning method.
   *
   * @param number the number of characters to be read again. This number must not be greater than
   *     {@link #yylength()}.
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
    
  yyclose();    }
  }




  /**
   * Resumes scanning until the next regular expression is matched, the end of input is encountered
   * or an I/O-Error occurs.
   *
   * @return the next token.
   * @exception java.io.IOException if any I/O-Error occurs.
   */
  @Override  public java_cup.runtime.Symbol next_token() throws java.io.IOException
  {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char[] zzBufferL = zzBuffer;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':  // fall through
        case '\u000C':  // fall through
        case '\u0085':  // fall through
        case '\u2028':  // fall through
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is
        // (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof)
            zzPeek = false;
          else
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMap(zzInput) ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
            zzDoEOF();
          { return new java_cup.runtime.Symbol(sym.EOF); }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1:
            { System.out.println("Lexical error at line " + yyline +
                       ", column " + yycolumn +
                       ": " + yytext());
            }
          // fall through
          case 52: break;
          case 2:
            { 
            }
          // fall through
          case 53: break;
          case 3:
            { return new Symbol(sym.T_HASH);
            }
          // fall through
          case 54: break;
          case 4:
            { return new Symbol(sym.T_LPAR);
            }
          // fall through
          case 55: break;
          case 5:
            { return new Symbol(sym.T_RPAR);
            }
          // fall through
          case 56: break;
          case 6:
            { return new Symbol(sym.T_TIMES);
            }
          // fall through
          case 57: break;
          case 7:
            { return new Symbol(sym.T_PLUS);
            }
          // fall through
          case 58: break;
          case 8:
            { return new Symbol(sym.T_COMMA);
            }
          // fall through
          case 59: break;
          case 9:
            { return new Symbol(sym.T_MINUS);
            }
          // fall through
          case 60: break;
          case 10:
            { return new Symbol(sym.T_DIV);
            }
          // fall through
          case 61: break;
          case 11:
            { return new Symbol(sym.T_NUM , Integer.parseInt(yytext()));
            }
          // fall through
          case 62: break;
          case 12:
            { return new Symbol(sym.T_COLON);
            }
          // fall through
          case 63: break;
          case 13:
            { return new Symbol(sym.T_SEMICOLON);
            }
          // fall through
          case 64: break;
          case 14:
            { return new Symbol(sym.T_LT);
            }
          // fall through
          case 65: break;
          case 15:
            { return new Symbol(sym.T_EQ);
            }
          // fall through
          case 66: break;
          case 16:
            { return new Symbol(sym.T_GT);
            }
          // fall through
          case 67: break;
          case 17:
            { return new Symbol(sym.T_ID , yytext());
            }
          // fall through
          case 68: break;
          case 18:
            { return new Symbol(sym.T_LBRACKET);
            }
          // fall through
          case 69: break;
          case 19:
            { return new Symbol(sym.T_RBRACKET);
            }
          // fall through
          case 70: break;
          case 20:
            { return new Symbol(sym.T_STRING , yytext());
            }
          // fall through
          case 71: break;
          case 21:
            { return new Symbol(sym.T_ASSIGN);
            }
          // fall through
          case 72: break;
          case 22:
            { return new Symbol(sym.T_LE);
            }
          // fall through
          case 73: break;
          case 23:
            { return new Symbol(sym.T_NEQ);
            }
          // fall through
          case 74: break;
          case 24:
            { return new Symbol(sym.T_GE);
            }
          // fall through
          case 75: break;
          case 25:
            { return new Symbol(sym.T_IF);
            }
          // fall through
          case 76: break;
          case 26:
            { return new Symbol(sym.T_OR);
            }
          // fall through
          case 77: break;
          case 27:
            { return new Symbol(sym.T_CHARCONST , yytext());
            }
          // fall through
          case 78: break;
          case 28:
            { return new Symbol(sym.T_AND);
            }
          // fall through
          case 79: break;
          case 29:
            { return new Symbol(sym.T_DEF);
            }
          // fall through
          case 80: break;
          case 30:
            { return new Symbol(sym.T_END);
            }
          // fall through
          case 81: break;
          case 31:
            { return new Symbol(sym.T_FOR);
            }
          // fall through
          case 82: break;
          case 32:
            { return new Symbol(sym.T_INT);
            }
          // fall through
          case 83: break;
          case 33:
            { return new Symbol(sym.T_MOD);
            }
          // fall through
          case 84: break;
          case 34:
            { return new Symbol(sym.T_NEW);
            }
          // fall through
          case 85: break;
          case 35:
            { return new Symbol(sym.T_NIL);
            }
          // fall through
          case 86: break;
          case 36:
            { return new Symbol(sym.T_NOT);
            }
          // fall through
          case 87: break;
          case 37:
            { return new Symbol(sym.T_REF);
            }
          // fall through
          case 88: break;
          case 38:
            { return new Symbol(sym.T_BOOL);
            }
          // fall through
          case 89: break;
          case 39:
            { return new Symbol(sym.T_CHAR);
            }
          // fall through
          case 90: break;
          case 40:
            { return new Symbol(sym.T_DECL);
            }
          // fall through
          case 91: break;
          case 41:
            { return new Symbol(sym.T_ELSE);
            }
          // fall through
          case 92: break;
          case 42:
            { return new Symbol(sym.T_EXIT);
            }
          // fall through
          case 93: break;
          case 43:
            { return new Symbol(sym.T_HEAD);
            }
          // fall through
          case 94: break;
          case 44:
            { return new Symbol(sym.T_LIST);
            }
          // fall through
          case 95: break;
          case 45:
            { return new Symbol(sym.T_NILQ);
            }
          // fall through
          case 96: break;
          case 46:
            { return new Symbol(sym.T_SKIP);
            }
          // fall through
          case 97: break;
          case 47:
            { return new Symbol(sym.T_TAIL);
            }
          // fall through
          case 98: break;
          case 48:
            { return new Symbol(sym.T_TRUE);
            }
          // fall through
          case 99: break;
          case 49:
            { return new Symbol(sym.T_ELSIF);
            }
          // fall through
          case 100: break;
          case 50:
            { return new Symbol(sym.T_FALSE);
            }
          // fall through
          case 101: break;
          case 51:
            { return new Symbol(sym.T_RETURN);
            }
          // fall through
          case 102: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
