
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

import java_cup.runtime.*;
import java.util.*;
import symbol.*;
import ast.*;
import types.*;
import errors.*;
import java_cup.runtime.XMLElement;

/** CUP v0.11b 20160615 (GIT 4ac7450) generated parser.
  */
@SuppressWarnings({"rawtypes"})
public class parser extends java_cup.runtime.lr_parser {

 public final Class getSymbolContainer() {
    return sym.class;
}

  /** Default constructor. */
  @Deprecated
  public parser() {super();}

  /** Constructor which sets the default scanner. */
  @Deprecated
  public parser(java_cup.runtime.Scanner s) {super(s);}

  /** Constructor which sets the default scanner. */
  public parser(java_cup.runtime.Scanner s, java_cup.runtime.SymbolFactory sf) {super(s,sf);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\116\000\002\002\004\000\002\002\003\000\002\003" +
    "\004\000\002\003\003\000\002\004\010\000\002\031\006" +
    "\000\002\031\007\000\002\024\005\000\002\024\003\000" +
    "\002\025\003\000\002\025\002\000\002\026\004\000\002" +
    "\026\005\000\002\027\003\000\002\027\005\000\002\027" +
    "\006\000\002\030\003\000\002\030\003\000\002\030\003" +
    "\000\002\023\005\000\002\023\003\000\002\005\004\000" +
    "\002\005\002\000\002\006\003\000\002\006\004\000\002" +
    "\007\004\000\002\007\003\000\002\010\005\000\002\010" +
    "\003\000\002\011\003\000\002\011\004\000\002\011\003" +
    "\000\002\011\011\000\002\011\013\000\002\014\007\000" +
    "\002\014\002\000\002\013\005\000\002\013\002\000\002" +
    "\012\003\000\002\012\005\000\002\012\003\000\002\020" +
    "\005\000\002\020\006\000\002\021\005\000\002\021\003" +
    "\000\002\017\003\000\002\017\006\000\002\016\003\000" +
    "\002\016\003\000\002\016\003\000\002\016\003\000\002" +
    "\016\003\000\002\016\003\000\002\016\003\000\002\016" +
    "\003\000\002\016\005\000\002\016\007\000\002\015\003" +
    "\000\002\015\004\000\002\015\004\000\002\015\004\000" +
    "\002\015\004\000\002\015\004\000\002\015\004\000\002" +
    "\015\005\000\002\015\005\000\002\015\005\000\002\015" +
    "\005\000\002\015\005\000\002\015\005\000\002\015\005" +
    "\000\002\015\005\000\002\015\005\000\002\015\005\000" +
    "\002\015\005\000\002\015\005\000\002\015\005\000\002" +
    "\015\005" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\230\000\004\010\005\001\002\000\004\002\232\001" +
    "\002\000\014\005\011\006\012\021\017\022\013\062\016" +
    "\001\002\000\006\002\ufffe\010\ufffe\001\002\000\006\002" +
    "\000\010\005\001\002\000\006\002\uffff\010\uffff\001\002" +
    "\000\010\040\ufff0\041\ufff0\062\ufff0\001\002\000\010\040" +
    "\uffef\041\uffef\062\uffef\001\002\000\004\040\227\001\002" +
    "\000\010\040\ufff4\041\ufff4\062\ufff4\001\002\000\006\040" +
    "\202\062\223\001\002\000\004\036\207\001\002\000\010" +
    "\040\ufff1\041\ufff1\062\ufff1\001\002\000\004\044\021\001" +
    "\002\000\030\005\uffeb\006\uffeb\010\uffeb\014\uffeb\016\uffeb" +
    "\020\uffeb\021\uffeb\022\uffeb\032\uffeb\033\uffeb\062\uffeb\001" +
    "\002\000\030\005\011\006\012\010\005\014\034\016\035" +
    "\020\026\021\017\022\013\032\031\033\033\062\030\001" +
    "\002\000\030\005\uffea\006\uffea\010\uffea\014\uffea\016\uffea" +
    "\020\uffea\021\uffea\022\uffea\032\uffea\033\uffea\062\uffea\001" +
    "\002\000\006\040\202\062\204\001\002\000\024\011\uffe4" +
    "\012\uffe4\013\uffe4\014\uffe4\016\uffe4\020\uffe4\032\uffe4\033" +
    "\uffe4\062\uffe4\001\002\000\040\015\051\017\052\024\057" +
    "\025\053\026\064\027\046\034\055\035\044\036\056\046" +
    "\063\047\047\062\030\063\060\064\050\065\054\001\002" +
    "\000\020\013\164\014\034\016\035\020\026\032\031\033" +
    "\033\062\030\001\002\000\100\004\uffd4\011\uffd4\012\uffd4" +
    "\013\uffd4\014\uffd4\016\uffd4\020\uffd4\023\uffd4\030\uffd4\032" +
    "\uffd4\033\uffd4\036\155\037\uffd4\040\uffd4\041\uffd4\042\uffd4" +
    "\043\uffd4\044\uffd4\045\uffd4\046\uffd4\047\uffd4\050\uffd4\051" +
    "\uffd4\052\uffd4\053\uffd4\054\uffd4\055\uffd4\056\uffd4\057\uffd4" +
    "\060\uffd4\062\uffd4\001\002\000\040\015\051\017\052\024" +
    "\057\025\053\026\064\027\046\034\055\035\044\036\056" +
    "\046\063\047\047\062\030\063\060\064\050\065\054\001" +
    "\002\000\030\005\uffec\006\uffec\010\uffec\014\uffec\016\uffec" +
    "\020\uffec\021\uffec\022\uffec\032\uffec\033\uffec\062\uffec\001" +
    "\002\000\032\011\uffdb\012\uffdb\013\uffdb\014\uffdb\016\uffdb" +
    "\020\uffdb\032\uffdb\033\uffdb\042\uffdb\043\uffdb\044\uffdb\062" +
    "\uffdb\001\002\000\024\011\uffe2\012\uffe2\013\uffe2\014\uffe2" +
    "\016\uffe2\020\uffe2\032\uffe2\033\uffe2\062\uffe2\001\002\000" +
    "\006\033\033\062\030\001\002\000\032\011\uffd9\012\uffd9" +
    "\013\uffd9\014\uffd9\016\uffd9\020\uffd9\032\uffd9\033\uffd9\042" +
    "\uffd9\043\uffd9\044\uffd9\062\uffd9\001\002\000\006\040\041" +
    "\045\042\001\002\000\024\011\uffe7\012\uffe7\013\uffe7\014" +
    "\uffe7\016\uffe7\020\uffe7\032\uffe7\033\uffe7\062\uffe7\001\002" +
    "\000\040\015\051\017\052\024\057\025\053\026\064\027" +
    "\046\034\055\035\044\036\056\046\063\047\047\062\030" +
    "\063\060\064\050\065\054\001\002\000\040\015\051\017" +
    "\052\024\057\025\053\026\064\027\046\034\055\035\044" +
    "\036\056\046\063\047\047\062\030\063\060\064\050\065" +
    "\054\001\002\000\072\004\uffc8\011\uffc8\012\uffc8\013\uffc8" +
    "\014\uffc8\016\uffc8\020\uffc8\023\uffc8\030\uffc8\032\uffc8\033" +
    "\uffc8\037\uffc8\041\uffc8\042\uffc8\043\uffc8\044\uffc8\046\uffc8" +
    "\047\uffc8\050\uffc8\051\uffc8\052\uffc8\053\uffc8\054\uffc8\055" +
    "\uffc8\056\uffc8\057\uffc8\060\uffc8\062\uffc8\001\002\000\072" +
    "\004\uffcf\011\uffcf\012\uffcf\013\uffcf\014\uffcf\016\uffcf\020" +
    "\uffcf\023\uffcf\030\uffcf\032\uffcf\033\uffcf\037\uffcf\041\uffcf" +
    "\042\uffcf\043\uffcf\044\uffcf\046\uffcf\047\uffcf\050\uffcf\051" +
    "\uffcf\052\uffcf\053\uffcf\054\uffcf\055\uffcf\056\uffcf\057\uffcf" +
    "\060\uffcf\062\uffcf\001\002\000\066\004\103\011\uffda\012" +
    "\uffda\013\uffda\014\uffda\016\uffda\020\uffda\023\071\030\100" +
    "\032\uffda\033\uffda\042\uffda\043\uffda\044\uffda\046\066\047" +
    "\101\050\076\051\075\052\070\053\073\054\077\055\074" +
    "\056\072\057\067\060\102\062\uffda\001\002\000\040\015" +
    "\051\017\052\024\057\025\053\026\064\027\046\034\055" +
    "\035\044\036\056\046\063\047\047\062\030\063\060\064" +
    "\050\065\054\001\002\000\040\015\051\017\052\024\057" +
    "\025\053\026\064\027\046\034\055\035\044\036\056\046" +
    "\063\047\047\062\030\063\060\064\050\065\054\001\002" +
    "\000\072\004\uffd0\011\uffd0\012\uffd0\013\uffd0\014\uffd0\016" +
    "\uffd0\020\uffd0\023\uffd0\030\uffd0\032\uffd0\033\uffd0\037\uffd0" +
    "\041\uffd0\042\uffd0\043\uffd0\044\uffd0\046\uffd0\047\uffd0\050" +
    "\uffd0\051\uffd0\052\uffd0\053\uffd0\054\uffd0\055\uffd0\056\uffd0" +
    "\057\uffd0\060\uffd0\062\uffd0\001\002\000\072\004\uffce\011" +
    "\uffce\012\uffce\013\uffce\014\uffce\016\uffce\020\uffce\023\uffce" +
    "\030\uffce\032\uffce\033\uffce\037\uffce\041\uffce\042\uffce\043" +
    "\uffce\044\uffce\046\uffce\047\uffce\050\uffce\051\uffce\052\uffce" +
    "\053\uffce\054\uffce\055\uffce\056\uffce\057\uffce\060\uffce\062" +
    "\uffce\001\002\000\040\015\051\017\052\024\057\025\053" +
    "\026\064\027\046\034\055\035\044\036\056\046\063\047" +
    "\047\062\030\063\060\064\050\065\054\001\002\000\072" +
    "\004\uffcd\011\uffcd\012\uffcd\013\uffcd\014\uffcd\016\uffcd\020" +
    "\uffcd\023\uffcd\030\uffcd\032\uffcd\033\uffcd\037\uffcd\041\uffcd" +
    "\042\uffcd\043\uffcd\044\uffcd\046\uffcd\047\uffcd\050\uffcd\051" +
    "\uffcd\052\uffcd\053\uffcd\054\uffcd\055\uffcd\056\uffcd\057\uffcd" +
    "\060\uffcd\062\uffcd\001\002\000\072\004\uffd2\011\uffd2\012" +
    "\uffd2\013\uffd2\014\uffd2\016\uffd2\020\uffd2\023\uffd2\030\uffd2" +
    "\032\uffd2\033\uffd2\037\uffd2\041\uffd2\042\uffd2\043\uffd2\044" +
    "\uffd2\046\uffd2\047\uffd2\050\uffd2\051\uffd2\052\uffd2\053\uffd2" +
    "\054\uffd2\055\uffd2\056\uffd2\057\uffd2\060\uffd2\062\uffd2\001" +
    "\002\000\040\015\051\017\052\024\057\025\053\026\064" +
    "\027\046\034\055\035\044\036\056\046\063\047\047\062" +
    "\030\063\060\064\050\065\054\001\002\000\040\015\051" +
    "\017\052\024\057\025\053\026\064\027\046\034\055\035" +
    "\044\036\056\046\063\047\047\062\030\063\060\064\050" +
    "\065\054\001\002\000\012\005\011\006\012\021\017\022" +
    "\013\001\002\000\072\004\uffd1\011\uffd1\012\uffd1\013\uffd1" +
    "\014\uffd1\016\uffd1\020\uffd1\023\uffd1\030\uffd1\032\uffd1\033" +
    "\uffd1\037\uffd1\041\uffd1\042\uffd1\043\uffd1\044\uffd1\046\uffd1" +
    "\047\uffd1\050\uffd1\051\uffd1\052\uffd1\053\uffd1\054\uffd1\055" +
    "\uffd1\056\uffd1\057\uffd1\060\uffd1\062\uffd1\001\002\000\072" +
    "\004\uffcb\011\uffcb\012\uffcb\013\uffcb\014\uffcb\016\uffcb\020" +
    "\uffcb\023\uffcb\030\uffcb\032\uffcb\033\uffcb\037\uffcb\041\uffcb" +
    "\042\uffcb\043\uffcb\044\uffcb\046\uffcb\047\uffcb\050\uffcb\051" +
    "\uffcb\052\uffcb\053\uffcb\054\uffcb\055\uffcb\056\uffcb\057\uffcb" +
    "\060\uffcb\062\uffcb\001\002\000\074\004\uffcc\011\uffcc\012" +
    "\uffcc\013\uffcc\014\uffcc\016\uffcc\020\uffcc\023\uffcc\030\uffcc" +
    "\032\uffcc\033\uffcc\037\uffcc\040\041\041\uffcc\042\uffcc\043" +
    "\uffcc\044\uffcc\046\uffcc\047\uffcc\050\uffcc\051\uffcc\052\uffcc" +
    "\053\uffcc\054\uffcc\055\uffcc\056\uffcc\057\uffcc\060\uffcc\062" +
    "\uffcc\001\002\000\040\015\051\017\052\024\057\025\053" +
    "\026\064\027\046\034\055\035\044\036\056\046\063\047" +
    "\047\062\030\063\060\064\050\065\054\001\002\000\040" +
    "\015\051\017\052\024\057\025\053\026\064\027\046\034" +
    "\055\035\044\036\056\046\063\047\047\062\030\063\060" +
    "\064\050\065\054\001\002\000\072\004\103\011\uffc2\012" +
    "\uffc2\013\uffc2\014\uffc2\016\uffc2\020\uffc2\023\071\030\100" +
    "\032\uffc2\033\uffc2\037\uffc2\041\uffc2\042\uffc2\043\uffc2\044" +
    "\uffc2\046\066\047\101\050\076\051\075\052\070\053\073" +
    "\054\077\055\074\056\072\057\067\060\102\062\uffc2\001" +
    "\002\000\040\015\051\017\052\024\057\025\053\026\064" +
    "\027\046\034\055\035\044\036\056\046\063\047\047\062" +
    "\030\063\060\064\050\065\054\001\002\000\040\015\051" +
    "\017\052\024\057\025\053\026\064\027\046\034\055\035" +
    "\044\036\056\046\063\047\047\062\030\063\060\064\050" +
    "\065\054\001\002\000\040\015\051\017\052\024\057\025" +
    "\053\026\064\027\046\034\055\035\044\036\056\046\063" +
    "\047\047\062\030\063\060\064\050\065\054\001\002\000" +
    "\040\015\051\017\052\024\057\025\053\026\064\027\046" +
    "\034\055\035\044\036\056\046\063\047\047\062\030\063" +
    "\060\064\050\065\054\001\002\000\040\015\051\017\052" +
    "\024\057\025\053\026\064\027\046\034\055\035\044\036" +
    "\056\046\063\047\047\062\030\063\060\064\050\065\054" +
    "\001\002\000\040\015\051\017\052\024\057\025\053\026" +
    "\064\027\046\034\055\035\044\036\056\046\063\047\047" +
    "\062\030\063\060\064\050\065\054\001\002\000\040\015" +
    "\051\017\052\024\057\025\053\026\064\027\046\034\055" +
    "\035\044\036\056\046\063\047\047\062\030\063\060\064" +
    "\050\065\054\001\002\000\040\015\051\017\052\024\057" +
    "\025\053\026\064\027\046\034\055\035\044\036\056\046" +
    "\063\047\047\062\030\063\060\064\050\065\054\001\002" +
    "\000\040\015\051\017\052\024\057\025\053\026\064\027" +
    "\046\034\055\035\044\036\056\046\063\047\047\062\030" +
    "\063\060\064\050\065\054\001\002\000\040\015\051\017" +
    "\052\024\057\025\053\026\064\027\046\034\055\035\044" +
    "\036\056\046\063\047\047\062\030\063\060\064\050\065" +
    "\054\001\002\000\040\015\051\017\052\024\057\025\053" +
    "\026\064\027\046\034\055\035\044\036\056\046\063\047" +
    "\047\062\030\063\060\064\050\065\054\001\002\000\040" +
    "\015\051\017\052\024\057\025\053\026\064\027\046\034" +
    "\055\035\044\036\056\046\063\047\047\062\030\063\060" +
    "\064\050\065\054\001\002\000\040\015\051\017\052\024" +
    "\057\025\053\026\064\027\046\034\055\035\044\036\056" +
    "\046\063\047\047\062\030\063\060\064\050\065\054\001" +
    "\002\000\040\015\051\017\052\024\057\025\053\026\064" +
    "\027\046\034\055\035\044\036\056\046\063\047\047\062" +
    "\030\063\060\064\050\065\054\001\002\000\072\004\uffb6" +
    "\011\uffb6\012\uffb6\013\uffb6\014\uffb6\016\uffb6\020\uffb6\023" +
    "\071\030\uffb6\032\uffb6\033\uffb6\037\uffb6\041\uffb6\042\uffb6" +
    "\043\uffb6\044\uffb6\046\066\047\101\050\076\051\075\052" +
    "\070\053\073\054\077\055\074\056\072\057\067\060\uffb6" +
    "\062\uffb6\001\002\000\072\004\103\011\uffb4\012\uffb4\013" +
    "\uffb4\014\uffb4\016\uffb4\020\uffb4\023\071\030\100\032\uffb4" +
    "\033\uffb4\037\uffb4\041\uffb4\042\uffb4\043\uffb4\044\uffb4\046" +
    "\066\047\101\050\076\051\075\052\070\053\073\054\077" +
    "\055\074\056\072\057\067\060\102\062\uffb4\001\002\000" +
    "\072\004\uffc0\011\uffc0\012\uffc0\013\uffc0\014\uffc0\016\uffc0" +
    "\020\uffc0\023\071\030\uffc0\032\uffc0\033\uffc0\037\uffc0\041" +
    "\uffc0\042\uffc0\043\uffc0\044\uffc0\046\uffc0\047\uffc0\050\076" +
    "\051\075\052\uffc0\053\uffc0\054\uffc0\055\uffc0\056\uffc0\057" +
    "\uffc0\060\uffc0\062\uffc0\001\002\000\072\004\103\011\uffb5" +
    "\012\uffb5\013\uffb5\014\uffb5\016\uffb5\020\uffb5\023\071\030" +
    "\uffb5\032\uffb5\033\uffb5\037\uffb5\041\uffb5\042\uffb5\043\uffb5" +
    "\044\uffb5\046\066\047\101\050\076\051\075\052\070\053" +
    "\073\054\077\055\074\056\072\057\067\060\uffb5\062\uffb5" +
    "\001\002\000\056\004\uffba\011\uffba\012\uffba\013\uffba\014" +
    "\uffba\016\uffba\020\uffba\023\071\030\uffba\032\uffba\033\uffba" +
    "\037\uffba\041\uffba\042\uffba\043\uffba\044\uffba\046\066\047" +
    "\101\050\076\051\075\060\uffba\062\uffba\001\002\000\072" +
    "\004\uffbf\011\uffbf\012\uffbf\013\uffbf\014\uffbf\016\uffbf\020" +
    "\uffbf\023\uffbf\030\uffbf\032\uffbf\033\uffbf\037\uffbf\041\uffbf" +
    "\042\uffbf\043\uffbf\044\uffbf\046\uffbf\047\uffbf\050\uffbf\051" +
    "\uffbf\052\uffbf\053\uffbf\054\uffbf\055\uffbf\056\uffbf\057\uffbf" +
    "\060\uffbf\062\uffbf\001\002\000\072\004\uffbe\011\uffbe\012" +
    "\uffbe\013\uffbe\014\uffbe\016\uffbe\020\uffbe\023\uffbe\030\uffbe" +
    "\032\uffbe\033\uffbe\037\uffbe\041\uffbe\042\uffbe\043\uffbe\044" +
    "\uffbe\046\uffbe\047\uffbe\050\uffbe\051\uffbe\052\uffbe\053\uffbe" +
    "\054\uffbe\055\uffbe\056\uffbe\057\uffbe\060\uffbe\062\uffbe\001" +
    "\002\000\056\004\uffb9\011\uffb9\012\uffb9\013\uffb9\014\uffb9" +
    "\016\uffb9\020\uffb9\023\071\030\uffb9\032\uffb9\033\uffb9\037" +
    "\uffb9\041\uffb9\042\uffb9\043\uffb9\044\uffb9\046\066\047\101" +
    "\050\076\051\075\060\uffb9\062\uffb9\001\002\000\056\004" +
    "\uffbb\011\uffbb\012\uffbb\013\uffbb\014\uffbb\016\uffbb\020\uffbb" +
    "\023\071\030\uffbb\032\uffbb\033\uffbb\037\uffbb\041\uffbb\042" +
    "\uffbb\043\uffbb\044\uffbb\046\066\047\101\050\076\051\075" +
    "\060\uffbb\062\uffbb\001\002\000\056\004\uffb8\011\uffb8\012" +
    "\uffb8\013\uffb8\014\uffb8\016\uffb8\020\uffb8\023\071\030\uffb8" +
    "\032\uffb8\033\uffb8\037\uffb8\041\uffb8\042\uffb8\043\uffb8\044" +
    "\uffb8\046\066\047\101\050\076\051\075\060\uffb8\062\uffb8" +
    "\001\002\000\072\004\uffbd\011\uffbd\012\uffbd\013\uffbd\014" +
    "\uffbd\016\uffbd\020\uffbd\023\uffbd\030\uffbd\032\uffbd\033\uffbd" +
    "\037\uffbd\041\uffbd\042\uffbd\043\uffbd\044\uffbd\046\uffbd\047" +
    "\uffbd\050\uffbd\051\uffbd\052\uffbd\053\uffbd\054\uffbd\055\uffbd" +
    "\056\uffbd\057\uffbd\060\uffbd\062\uffbd\001\002\000\056\004" +
    "\uffbc\011\uffbc\012\uffbc\013\uffbc\014\uffbc\016\uffbc\020\uffbc" +
    "\023\071\030\uffbc\032\uffbc\033\uffbc\037\uffbc\041\uffbc\042" +
    "\uffbc\043\uffbc\044\uffbc\046\066\047\101\050\076\051\075" +
    "\060\uffbc\062\uffbc\001\002\000\056\004\uffb7\011\uffb7\012" +
    "\uffb7\013\uffb7\014\uffb7\016\uffb7\020\uffb7\023\071\030\uffb7" +
    "\032\uffb7\033\uffb7\037\uffb7\041\uffb7\042\uffb7\043\uffb7\044" +
    "\uffb7\046\066\047\101\050\076\051\075\060\uffb7\062\uffb7" +
    "\001\002\000\072\004\uffc1\011\uffc1\012\uffc1\013\uffc1\014" +
    "\uffc1\016\uffc1\020\uffc1\023\071\030\uffc1\032\uffc1\033\uffc1" +
    "\037\uffc1\041\uffc1\042\uffc1\043\uffc1\044\uffc1\046\uffc1\047" +
    "\uffc1\050\076\051\075\052\uffc1\053\uffc1\054\uffc1\055\uffc1" +
    "\056\uffc1\057\uffc1\060\uffc1\062\uffc1\001\002\000\072\004" +
    "\uffc6\011\uffc6\012\uffc6\013\uffc6\014\uffc6\016\uffc6\020\uffc6" +
    "\023\uffc6\030\uffc6\032\uffc6\033\uffc6\037\uffc6\041\uffc6\042" +
    "\uffc6\043\uffc6\044\uffc6\046\uffc6\047\uffc6\050\uffc6\051\uffc6" +
    "\052\uffc6\053\uffc6\054\uffc6\055\uffc6\056\uffc6\057\uffc6\060" +
    "\uffc6\062\uffc6\001\002\000\004\040\124\001\002\000\042" +
    "\015\051\017\052\024\057\025\053\026\064\027\046\034" +
    "\055\035\044\036\056\041\126\046\063\047\047\062\030" +
    "\063\060\064\050\065\054\001\002\000\040\004\103\023" +
    "\071\030\100\041\127\046\066\047\101\050\076\051\075" +
    "\052\070\053\073\054\077\055\074\056\072\057\067\060" +
    "\102\001\002\000\010\040\ufff3\041\ufff3\062\ufff3\001\002" +
    "\000\072\004\uffc9\011\uffc9\012\uffc9\013\uffc9\014\uffc9\016" +
    "\uffc9\020\uffc9\023\uffc9\030\uffc9\032\uffc9\033\uffc9\037\uffc9" +
    "\041\uffc9\042\uffc9\043\uffc9\044\uffc9\046\uffc9\047\uffc9\050" +
    "\uffc9\051\uffc9\052\uffc9\053\uffc9\054\uffc9\055\uffc9\056\uffc9" +
    "\057\uffc9\060\uffc9\062\uffc9\001\002\000\040\004\103\023" +
    "\071\030\100\037\131\046\066\047\101\050\076\051\075" +
    "\052\070\053\073\054\077\055\074\056\072\057\067\060" +
    "\102\001\002\000\072\004\uffca\011\uffca\012\uffca\013\uffca" +
    "\014\uffca\016\uffca\020\uffca\023\uffca\030\uffca\032\uffca\033" +
    "\uffca\037\uffca\041\uffca\042\uffca\043\uffca\044\uffca\046\uffca" +
    "\047\uffca\050\uffca\051\uffca\052\uffca\053\uffca\054\uffca\055" +
    "\uffca\056\uffca\057\uffca\060\uffca\062\uffca\001\002\000\072" +
    "\004\103\011\uffc3\012\uffc3\013\uffc3\014\uffc3\016\uffc3\020" +
    "\uffc3\023\071\030\100\032\uffc3\033\uffc3\037\uffc3\041\uffc3" +
    "\042\uffc3\043\uffc3\044\uffc3\046\066\047\101\050\076\051" +
    "\075\052\070\053\073\054\077\055\074\056\072\057\067" +
    "\060\102\062\uffc3\001\002\000\072\004\103\011\uffc4\012" +
    "\uffc4\013\uffc4\014\uffc4\016\uffc4\020\uffc4\023\071\030\100" +
    "\032\uffc4\033\uffc4\037\uffc4\041\uffc4\042\uffc4\043\uffc4\044" +
    "\uffc4\046\066\047\101\050\076\051\075\052\070\053\073" +
    "\054\077\055\074\056\072\057\067\060\102\062\uffc4\001" +
    "\002\000\072\004\uffc7\011\uffc7\012\uffc7\013\uffc7\014\uffc7" +
    "\016\uffc7\020\uffc7\023\uffc7\030\uffc7\032\uffc7\033\uffc7\037" +
    "\uffc7\041\uffc7\042\uffc7\043\uffc7\044\uffc7\046\uffc7\047\uffc7" +
    "\050\uffc7\051\uffc7\052\uffc7\053\uffc7\054\uffc7\055\uffc7\056" +
    "\uffc7\057\uffc7\060\uffc7\062\uffc7\001\002\000\072\004\uffc5" +
    "\011\uffc5\012\uffc5\013\uffc5\014\uffc5\016\uffc5\020\uffc5\023" +
    "\uffc5\030\uffc5\032\uffc5\033\uffc5\037\uffc5\041\uffc5\042\uffc5" +
    "\043\uffc5\044\uffc5\046\uffc5\047\uffc5\050\uffc5\051\uffc5\052" +
    "\uffc5\053\uffc5\054\uffc5\055\uffc5\056\uffc5\057\uffc5\060\uffc5" +
    "\062\uffc5\001\002\000\040\004\103\023\071\030\100\041" +
    "\137\046\066\047\101\050\076\051\075\052\070\053\073" +
    "\054\077\055\074\056\072\057\067\060\102\001\002\000" +
    "\076\004\uffd3\011\uffd3\012\uffd3\013\uffd3\014\uffd3\016\uffd3" +
    "\020\uffd3\023\uffd3\030\uffd3\032\uffd3\033\uffd3\037\uffd3\040" +
    "\uffd3\041\uffd3\042\uffd3\043\uffd3\044\uffd3\045\uffd3\046\uffd3" +
    "\047\uffd3\050\uffd3\051\uffd3\052\uffd3\053\uffd3\054\uffd3\055" +
    "\uffd3\056\uffd3\057\uffd3\060\uffd3\062\uffd3\001\002\000\006" +
    "\042\142\043\143\001\002\000\010\042\uffe5\043\uffe5\044" +
    "\uffe5\001\002\000\006\033\033\062\030\001\002\000\040" +
    "\015\051\017\052\024\057\025\053\026\064\027\046\034" +
    "\055\035\044\036\056\046\063\047\047\062\030\063\060" +
    "\064\050\065\054\001\002\000\040\004\103\023\071\030" +
    "\100\043\145\046\066\047\101\050\076\051\075\052\070" +
    "\053\073\054\077\055\074\056\072\057\067\060\102\001" +
    "\002\000\006\033\033\062\030\001\002\000\006\042\142" +
    "\044\147\001\002\000\016\014\034\016\035\020\026\032" +
    "\031\033\033\062\030\001\002\000\020\013\152\014\034" +
    "\016\035\020\026\032\031\033\033\062\030\001\002\000" +
    "\024\011\uffe8\012\uffe8\013\uffe8\014\uffe8\016\uffe8\020\uffe8" +
    "\032\uffe8\033\uffe8\062\uffe8\001\002\000\024\011\uffe0\012" +
    "\uffe0\013\uffe0\014\uffe0\016\uffe0\020\uffe0\032\uffe0\033\uffe0" +
    "\062\uffe0\001\002\000\010\042\uffe6\043\uffe6\044\uffe6\001" +
    "\002\000\060\004\103\011\uffe3\012\uffe3\013\uffe3\014\uffe3" +
    "\016\uffe3\020\uffe3\023\071\030\100\032\uffe3\033\uffe3\046" +
    "\066\047\101\050\076\051\075\052\070\053\073\054\077" +
    "\055\074\056\072\057\067\060\102\062\uffe3\001\002\000" +
    "\042\015\051\017\052\024\057\025\053\026\064\027\046" +
    "\034\055\035\044\036\056\037\157\046\063\047\047\062" +
    "\030\063\060\064\050\065\054\001\002\000\042\004\103" +
    "\023\071\030\100\037\uffd5\042\uffd5\046\066\047\101\050" +
    "\076\051\075\052\070\053\073\054\077\055\074\056\072" +
    "\057\067\060\102\001\002\000\072\004\uffd8\011\uffd8\012" +
    "\uffd8\013\uffd8\014\uffd8\016\uffd8\020\uffd8\023\uffd8\030\uffd8" +
    "\032\uffd8\033\uffd8\037\uffd8\041\uffd8\042\uffd8\043\uffd8\044" +
    "\uffd8\046\uffd8\047\uffd8\050\uffd8\051\uffd8\052\uffd8\053\uffd8" +
    "\054\uffd8\055\uffd8\056\uffd8\057\uffd8\060\uffd8\062\uffd8\001" +
    "\002\000\006\037\161\042\162\001\002\000\072\004\uffd7" +
    "\011\uffd7\012\uffd7\013\uffd7\014\uffd7\016\uffd7\020\uffd7\023" +
    "\uffd7\030\uffd7\032\uffd7\033\uffd7\037\uffd7\041\uffd7\042\uffd7" +
    "\043\uffd7\044\uffd7\046\uffd7\047\uffd7\050\uffd7\051\uffd7\052" +
    "\uffd7\053\uffd7\054\uffd7\055\uffd7\056\uffd7\057\uffd7\060\uffd7" +
    "\062\uffd7\001\002\000\040\015\051\017\052\024\057\025" +
    "\053\026\064\027\046\034\055\035\044\036\056\046\063" +
    "\047\047\062\030\063\060\064\050\065\054\001\002\000" +
    "\042\004\103\023\071\030\100\037\uffd6\042\uffd6\046\066" +
    "\047\101\050\076\051\075\052\070\053\073\054\077\055" +
    "\074\056\072\057\067\060\102\001\002\000\032\002\ufffd" +
    "\005\ufffd\006\ufffd\010\ufffd\014\ufffd\016\ufffd\020\ufffd\021" +
    "\ufffd\022\ufffd\032\ufffd\033\ufffd\062\ufffd\001\002\000\040" +
    "\004\103\023\071\030\100\044\166\046\066\047\101\050" +
    "\076\051\075\052\070\053\073\054\077\055\074\056\072" +
    "\057\067\060\102\001\002\000\016\014\034\016\035\020" +
    "\026\032\031\033\033\062\030\001\002\000\024\011\uffde" +
    "\012\uffde\013\uffde\014\034\016\035\020\026\032\031\033" +
    "\033\062\030\001\002\000\010\011\172\012\173\013\uffdc" +
    "\001\002\000\004\013\201\001\002\000\004\044\177\001" +
    "\002\000\040\015\051\017\052\024\057\025\053\026\064" +
    "\027\046\034\055\035\044\036\056\046\063\047\047\062" +
    "\030\063\060\064\050\065\054\001\002\000\040\004\103" +
    "\023\071\030\100\044\175\046\066\047\101\050\076\051" +
    "\075\052\070\053\073\054\077\055\074\056\072\057\067" +
    "\060\102\001\002\000\016\014\034\016\035\020\026\032" +
    "\031\033\033\062\030\001\002\000\024\011\uffdf\012\uffdf" +
    "\013\uffdf\014\034\016\035\020\026\032\031\033\033\062" +
    "\030\001\002\000\016\014\034\016\035\020\026\032\031" +
    "\033\033\062\030\001\002\000\020\013\uffdd\014\034\016" +
    "\035\020\026\032\031\033\033\062\030\001\002\000\024" +
    "\011\uffe1\012\uffe1\013\uffe1\014\uffe1\016\uffe1\020\uffe1\032" +
    "\uffe1\033\uffe1\062\uffe1\001\002\000\004\041\126\001\002" +
    "\000\032\005\uffe9\006\uffe9\010\uffe9\014\uffe9\016\uffe9\020" +
    "\uffe9\021\uffe9\022\uffe9\032\uffe9\033\uffe9\042\205\062\uffe9" +
    "\001\002\000\036\005\uffed\006\uffed\010\uffed\014\uffed\016" +
    "\uffed\020\uffed\021\uffed\022\uffed\032\uffed\033\uffed\037\uffed" +
    "\042\uffed\043\uffed\062\uffed\001\002\000\004\062\206\001" +
    "\002\000\036\005\uffee\006\uffee\010\uffee\014\uffee\016\uffee" +
    "\020\uffee\021\uffee\022\uffee\032\uffee\033\uffee\037\uffee\042" +
    "\uffee\043\uffee\062\uffee\001\002\000\016\005\011\006\012" +
    "\021\017\022\013\031\212\037\ufff7\001\002\000\006\037" +
    "\ufff9\043\ufff9\001\002\000\004\037\222\001\002\000\012" +
    "\005\011\006\012\021\017\022\013\001\002\000\006\040" +
    "\202\062\204\001\002\000\006\037\ufff8\043\215\001\002" +
    "\000\014\005\011\006\012\021\017\022\013\031\212\001" +
    "\002\000\006\037\ufffa\043\ufffa\001\002\000\010\037\ufff6" +
    "\042\205\043\ufff6\001\002\000\006\040\202\062\204\001" +
    "\002\000\010\037\ufff5\042\205\043\ufff5\001\002\000\004" +
    "\044\ufffc\001\002\000\004\036\224\001\002\000\016\005" +
    "\011\006\012\021\017\022\013\031\212\037\ufff7\001\002" +
    "\000\004\037\226\001\002\000\004\044\ufffb\001\002\000" +
    "\012\005\011\006\012\021\017\022\013\001\002\000\006" +
    "\040\202\041\231\001\002\000\010\040\ufff2\041\ufff2\062" +
    "\ufff2\001\002\000\004\002\001\001\002" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\230\000\010\002\003\003\006\004\005\001\001\000" +
    "\002\001\001\000\010\027\014\030\013\031\017\001\001" +
    "\000\002\001\001\000\004\004\007\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\004\005\021\001\001" +
    "\000\024\004\022\006\031\007\026\011\037\012\024\017" +
    "\036\020\035\027\023\030\013\001\001\000\002\001\001" +
    "\000\004\023\202\001\001\000\002\001\001\000\012\015" +
    "\164\016\042\017\061\020\060\001\001\000\012\011\150" +
    "\012\024\017\036\020\035\001\001\000\002\001\001\000" +
    "\012\015\153\016\042\017\061\020\060\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\012\010" +
    "\137\012\140\017\036\020\035\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\012\015\135\016" +
    "\042\017\061\020\060\001\001\000\012\015\044\016\042" +
    "\017\061\020\060\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\012\015\134\016\042\017\061" +
    "\020\060\001\001\000\012\015\133\016\042\017\061\020" +
    "\060\001\001\000\002\001\001\000\002\001\001\000\012" +
    "\015\132\016\042\017\061\020\060\001\001\000\002\001" +
    "\001\000\002\001\001\000\012\015\131\016\042\017\061" +
    "\020\060\001\001\000\012\015\127\016\042\017\061\020" +
    "\060\001\001\000\006\027\122\030\013\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\012\015" +
    "\121\016\042\017\061\020\060\001\001\000\012\015\064" +
    "\016\042\017\061\020\060\001\001\000\002\001\001\000" +
    "\012\015\120\016\042\017\061\020\060\001\001\000\012" +
    "\015\117\016\042\017\061\020\060\001\001\000\012\015" +
    "\116\016\042\017\061\020\060\001\001\000\012\015\115" +
    "\016\042\017\061\020\060\001\001\000\012\015\114\016" +
    "\042\017\061\020\060\001\001\000\012\015\113\016\042" +
    "\017\061\020\060\001\001\000\012\015\112\016\042\017" +
    "\061\020\060\001\001\000\012\015\111\016\042\017\061" +
    "\020\060\001\001\000\012\015\110\016\042\017\061\020" +
    "\060\001\001\000\012\015\107\016\042\017\061\020\060" +
    "\001\001\000\012\015\106\016\042\017\061\020\060\001" +
    "\001\000\012\015\105\016\042\017\061\020\060\001\001" +
    "\000\012\015\104\016\042\017\061\020\060\001\001\000" +
    "\012\015\103\016\042\017\061\020\060\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\012\015" +
    "\124\016\042\017\061\020\060\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\010\012\152" +
    "\017\036\020\035\001\001\000\012\015\143\016\042\017" +
    "\061\020\060\001\001\000\002\001\001\000\012\010\145" +
    "\012\140\017\036\020\035\001\001\000\002\001\001\000" +
    "\014\007\147\011\037\012\024\017\036\020\035\001\001" +
    "\000\012\011\150\012\024\017\036\020\035\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\014\015\155\016\042\017\061\020\060\021" +
    "\157\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\012\015\162\016\042\017" +
    "\061\020\060\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\014\007\166\011\037\012\024\017" +
    "\036\020\035\001\001\000\014\011\150\012\024\014\167" +
    "\017\036\020\035\001\001\000\004\013\170\001\001\000" +
    "\002\001\001\000\002\001\001\000\012\015\173\016\042" +
    "\017\061\020\060\001\001\000\002\001\001\000\014\007" +
    "\175\011\037\012\024\017\036\020\035\001\001\000\012" +
    "\011\150\012\024\017\036\020\035\001\001\000\014\007" +
    "\177\011\037\012\024\017\036\020\035\001\001\000\012" +
    "\011\150\012\024\017\036\020\035\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\014\024\213\025" +
    "\210\026\207\027\212\030\013\001\001\000\002\001\001" +
    "\000\002\001\001\000\006\027\217\030\013\001\001\000" +
    "\004\023\216\001\001\000\002\001\001\000\010\026\215" +
    "\027\212\030\013\001\001\000\002\001\001\000\002\001" +
    "\001\000\004\023\220\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\014\024\213\025\224\026" +
    "\207\027\212\030\013\001\001\000\002\001\001\000\002" +
    "\001\001\000\006\027\227\030\013\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$parser$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$parser$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$parser$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 0;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}



    public SymbolTable symbols = new SymbolTable();

    public void checkSemanticResult() {
        if (symbols.hasErrors()) {
            System.out.println("Semantic check completed with errors.");
        } else {
            System.out.println("Scope check OK");
        }
    }


/** Cup generated class to encapsulate user supplied action code.*/
@SuppressWarnings({"rawtypes", "unchecked", "unused"})
class CUP$parser$actions {
  private final parser parser;

  /** Constructor */
  CUP$parser$actions(parser parser) {
    this.parser = parser;
  }

  /** Method 0 with the actual generated action code for actions 0 to 300. */
  public final java_cup.runtime.Symbol CUP$parser$do_action_part00000000(
    int                        CUP$parser$act_num,
    java_cup.runtime.lr_parser CUP$parser$parser,
    java.util.Stack            CUP$parser$stack,
    int                        CUP$parser$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$parser$result;

      /* select the action based on the action number */
      switch (CUP$parser$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // $START ::= program EOF 
            {
              Object RESULT =null;
		int start_valleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int start_valright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		Program start_val = (Program)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		RESULT = start_val;
              CUP$parser$result = parser.getSymbolFactory().newSymbol("$START",0, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          /* ACCEPT */
          CUP$parser$parser.done_parsing();
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // program ::= def_list 
            {
              Program RESULT =null;
		int listleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int listright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		ArrayList<FuncDef> list = (ArrayList<FuncDef>)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		
        RESULT = new Program(list);
    
              CUP$parser$result = parser.getSymbolFactory().newSymbol("program",0, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: // def_list ::= def_list defn 
            {
              ArrayList<FuncDef> RESULT =null;
		int listleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int listright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		ArrayList<FuncDef> list = (ArrayList<FuncDef>)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		int fleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int fright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		FuncDef f = (FuncDef)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		
        list.add(f);
        RESULT = list;
    
              CUP$parser$result = parser.getSymbolFactory().newSymbol("def_list",1, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: // def_list ::= defn 
            {
              ArrayList<FuncDef> RESULT =null;
		int fleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int fright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		FuncDef f = (FuncDef)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		
        ArrayList<FuncDef> list = new ArrayList<FuncDef>();
        list.add(f);
        RESULT = list;
    
              CUP$parser$result = parser.getSymbolFactory().newSymbol("def_list",1, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 4: // defn ::= T_DEF header T_COLON local_list stmt_list T_END 
            {
              FuncDef RESULT =null;
		int hleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)).left;
		int hright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)).right;
		HeaderInfo h = (HeaderInfo)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-4)).value;
		int localsleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int localsright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		LocalList locals = (LocalList)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int stmtsleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int stmtsright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		ArrayList<Stmt> stmts = (ArrayList<Stmt>)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		
        RESULT = new FuncDef(
            h.name,
            h.returnType,
            h.params,
            locals.varDecls,
            locals.funcDefs,
            new BlockStmt(stmts)
        );
    
              CUP$parser$result = parser.getSymbolFactory().newSymbol("defn",2, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-5)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 5: // header ::= T_ID T_LPAR opt_formal_list T_RPAR 
            {
              HeaderInfo RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-3)).value;
		int paramsleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int paramsright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		ArrayList<Param> params = (ArrayList<Param>)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		
        RESULT = new HeaderInfo(
            id,
            BasicType.Void,
            params
        );
    
              CUP$parser$result = parser.getSymbolFactory().newSymbol("header",23, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 6: // header ::= type T_ID T_LPAR opt_formal_list T_RPAR 
            {
              HeaderInfo RESULT =null;
		int tleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)).left;
		int tright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)).right;
		String t = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-4)).value;
		int idleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-3)).value;
		int paramsleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int paramsright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		ArrayList<Param> params = (ArrayList<Param>)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		
        RESULT = new HeaderInfo(
            id,
            TypeConverter.fromString(t),
            params
        );
    
              CUP$parser$result = parser.getSymbolFactory().newSymbol("header",23, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 7: // formal_list ::= formal_list T_SEMICOLON formal 
            {
              ArrayList<Param> RESULT =null;
		int listleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int listright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		ArrayList<Param> list = (ArrayList<Param>)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int fleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int fright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Param f = (Param)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		
        list.add(f);
        RESULT = list;
    
              CUP$parser$result = parser.getSymbolFactory().newSymbol("formal_list",18, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 8: // formal_list ::= formal 
            {
              ArrayList<Param> RESULT =null;
		int fleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int fright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Param f = (Param)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		
        ArrayList<Param> list = new ArrayList<Param>();
        list.add(f);
        RESULT = list;
    
              CUP$parser$result = parser.getSymbolFactory().newSymbol("formal_list",18, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 9: // opt_formal_list ::= formal_list 
            {
              ArrayList<Param> RESULT =null;
		int listleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int listright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		ArrayList<Param> list = (ArrayList<Param>)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		
        RESULT = list;
    
              CUP$parser$result = parser.getSymbolFactory().newSymbol("opt_formal_list",19, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 10: // opt_formal_list ::= 
            {
              ArrayList<Param> RESULT =null;
		
        RESULT = new ArrayList<Param>();
    
              CUP$parser$result = parser.getSymbolFactory().newSymbol("opt_formal_list",19, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 11: // formal ::= type id_list 
            {
              Param RESULT =null;
		int tleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int tright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		String t = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		int idsleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int idsright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		ArrayList<String> ids = (ArrayList<String>)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		
        RESULT = new Param(
            TypeConverter.fromString(t),
            ids,
            false
        );
    
              CUP$parser$result = parser.getSymbolFactory().newSymbol("formal",20, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 12: // formal ::= T_REF type id_list 
            {
              Param RESULT =null;
		int tleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int tright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		String t = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		int idsleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int idsright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		ArrayList<String> ids = (ArrayList<String>)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		
        RESULT = new Param(
            TypeConverter.fromString(t),
            ids,
            true
        );
    
              CUP$parser$result = parser.getSymbolFactory().newSymbol("formal",20, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 13: // type ::= base_type 
            {
              String RESULT =null;
		int tleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int tright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		String t = (String)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		
        RESULT = t;
    
              CUP$parser$result = parser.getSymbolFactory().newSymbol("type",21, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 14: // type ::= type T_LBRACKET T_RBRACKET 
            {
              String RESULT =null;
		int tleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int tright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		String t = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		
        RESULT = t + "[]";
    
              CUP$parser$result = parser.getSymbolFactory().newSymbol("type",21, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 15: // type ::= T_LIST T_LBRACKET type T_RBRACKET 
            {
              String RESULT =null;
		int tleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int tright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		String t = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		
        RESULT = "list[" + t + "]";
    
              CUP$parser$result = parser.getSymbolFactory().newSymbol("type",21, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 16: // base_type ::= T_INT 
            {
              String RESULT =null;
		
        RESULT = "int";
    
              CUP$parser$result = parser.getSymbolFactory().newSymbol("base_type",22, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 17: // base_type ::= T_BOOL 
            {
              String RESULT =null;
		
        RESULT = "bool";
    
              CUP$parser$result = parser.getSymbolFactory().newSymbol("base_type",22, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 18: // base_type ::= T_CHAR 
            {
              String RESULT =null;
		
        RESULT = "char";
    
              CUP$parser$result = parser.getSymbolFactory().newSymbol("base_type",22, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 19: // id_list ::= id_list T_COMMA T_ID 
            {
              ArrayList<String> RESULT =null;
		int lleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int lright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		ArrayList<String> l = (ArrayList<String>)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int idleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int idright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		
        l.add(id);
        RESULT = l;
    
              CUP$parser$result = parser.getSymbolFactory().newSymbol("id_list",17, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 20: // id_list ::= T_ID 
            {
              ArrayList<String> RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int idright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		
        ArrayList<String> list = new ArrayList<String>();
        list.add(id);
        RESULT = list;
    
              CUP$parser$result = parser.getSymbolFactory().newSymbol("id_list",17, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 21: // local_list ::= local_list local_def 
            {
              LocalList RESULT =null;
		int listleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int listright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		LocalList list = (LocalList)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		int itemleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int itemright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Object item = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		
        if (item instanceof VarDecl) {
            list.addVarDecl((VarDecl)item);
        } else if (item instanceof FuncDef) {
            list.addFuncDef((FuncDef)item);
        }

        RESULT = list;
    
              CUP$parser$result = parser.getSymbolFactory().newSymbol("local_list",3, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 22: // local_list ::= 
            {
              LocalList RESULT =null;
		
        RESULT = new LocalList();
    
              CUP$parser$result = parser.getSymbolFactory().newSymbol("local_list",3, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 23: // local_def ::= defn 
            {
              Object RESULT =null;
		int fleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int fright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		FuncDef f = (FuncDef)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		
        RESULT = f;
    
              CUP$parser$result = parser.getSymbolFactory().newSymbol("local_def",4, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 24: // local_def ::= type id_list 
            {
              Object RESULT =null;
		int tleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int tright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		String t = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		int idsleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int idsright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		ArrayList<String> ids = (ArrayList<String>)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		
        RESULT = new VarDecl(
            TypeConverter.fromString(t),
            ids
        );
    
              CUP$parser$result = parser.getSymbolFactory().newSymbol("local_def",4, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 25: // stmt_list ::= stmt_list stmt 
            {
              ArrayList<Stmt> RESULT =null;
		int listleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int listright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		ArrayList<Stmt> list = (ArrayList<Stmt>)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		int sleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int sright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Stmt s = (Stmt)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		
        list.add(s);
        RESULT = list;
    
              CUP$parser$result = parser.getSymbolFactory().newSymbol("stmt_list",5, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 26: // stmt_list ::= stmt 
            {
              ArrayList<Stmt> RESULT =null;
		int sleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int sright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Stmt s = (Stmt)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		
        ArrayList<Stmt> list = new ArrayList<Stmt>();
        list.add(s);
        RESULT = list;
    
              CUP$parser$result = parser.getSymbolFactory().newSymbol("stmt_list",5, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 27: // simple_list ::= simple_list T_COMMA simple_stmt 
            {
              ArrayList<Stmt> RESULT =null;
		int listleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int listright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		ArrayList<Stmt> list = (ArrayList<Stmt>)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int sleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int sright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Stmt s = (Stmt)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		
        list.add(s);
        RESULT = list;
    
              CUP$parser$result = parser.getSymbolFactory().newSymbol("simple_list",6, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 28: // simple_list ::= simple_stmt 
            {
              ArrayList<Stmt> RESULT =null;
		int sleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int sright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Stmt s = (Stmt)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		
        ArrayList<Stmt> list = new ArrayList<Stmt>();
        list.add(s);
        RESULT = list;
    
              CUP$parser$result = parser.getSymbolFactory().newSymbol("simple_list",6, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 29: // stmt ::= simple_stmt 
            {
              Stmt RESULT =null;
		int sleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int sright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Stmt s = (Stmt)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		
        RESULT = s;
    
              CUP$parser$result = parser.getSymbolFactory().newSymbol("stmt",7, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 30: // stmt ::= T_RETURN expr 
            {
              Stmt RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Expr e = (Expr)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		
        RESULT = new ReturnStmt(e);
    
              CUP$parser$result = parser.getSymbolFactory().newSymbol("stmt",7, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 31: // stmt ::= T_EXIT 
            {
              Stmt RESULT =null;
		
        RESULT = new ExitStmt();
    
              CUP$parser$result = parser.getSymbolFactory().newSymbol("stmt",7, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 32: // stmt ::= T_IF expr T_COLON stmt_list elsif_list else_part T_END 
            {
              Stmt RESULT =null;
		int cleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-5)).left;
		int cright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-5)).right;
		Expr c = (Expr)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-5)).value;
		int thenListleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).left;
		int thenListright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).right;
		ArrayList<Stmt> thenList = (ArrayList<Stmt>)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-3)).value;
		int elsifsleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int elsifsright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		ElsifList elsifs = (ElsifList)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int elseBlockleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int elseBlockright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		BlockStmt elseBlock = (BlockStmt)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		
        RESULT = new IfStmt(
            c,
            new BlockStmt(thenList),
            elsifs.getConditions(),
            elsifs.getBlocks(),
            elseBlock
        );
    
              CUP$parser$result = parser.getSymbolFactory().newSymbol("stmt",7, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-6)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 33: // stmt ::= T_FOR simple_list T_SEMICOLON expr T_SEMICOLON simple_list T_COLON stmt_list T_END 
            {
              Stmt RESULT =null;
		int initleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-7)).left;
		int initright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-7)).right;
		ArrayList<Stmt> init = (ArrayList<Stmt>)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-7)).value;
		int condleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-5)).left;
		int condright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-5)).right;
		Expr cond = (Expr)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-5)).value;
		int stepleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).left;
		int stepright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).right;
		ArrayList<Stmt> step = (ArrayList<Stmt>)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-3)).value;
		int bodyleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int bodyright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		ArrayList<Stmt> body = (ArrayList<Stmt>)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		
        RESULT = new ForStmt(
            init,
            cond,
            step,
            new BlockStmt(body)
        );
    
              CUP$parser$result = parser.getSymbolFactory().newSymbol("stmt",7, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-8)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 34: // elsif_list ::= elsif_list T_ELSIF expr T_COLON stmt_list 
            {
              ElsifList RESULT =null;
		int listleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)).left;
		int listright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)).right;
		ElsifList list = (ElsifList)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-4)).value;
		int cleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int cright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		Expr c = (Expr)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int stmtsleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int stmtsright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		ArrayList<Stmt> stmts = (ArrayList<Stmt>)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		
        list.add(c, new BlockStmt(stmts));
        RESULT = list;
    
              CUP$parser$result = parser.getSymbolFactory().newSymbol("elsif_list",10, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 35: // elsif_list ::= 
            {
              ElsifList RESULT =null;
		
        RESULT = new ElsifList();
    
              CUP$parser$result = parser.getSymbolFactory().newSymbol("elsif_list",10, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 36: // else_part ::= T_ELSE T_COLON stmt_list 
            {
              BlockStmt RESULT =null;
		int stmtsleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int stmtsright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		ArrayList<Stmt> stmts = (ArrayList<Stmt>)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		
        RESULT = new BlockStmt(stmts);
    
              CUP$parser$result = parser.getSymbolFactory().newSymbol("else_part",9, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 37: // else_part ::= 
            {
              BlockStmt RESULT =null;
		
        RESULT = null;
    
              CUP$parser$result = parser.getSymbolFactory().newSymbol("else_part",9, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 38: // simple_stmt ::= T_SKIP 
            {
              Stmt RESULT =null;
		
        RESULT = new SkipStmt();
    
              CUP$parser$result = parser.getSymbolFactory().newSymbol("simple_stmt",8, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 39: // simple_stmt ::= lvalue T_ASSIGN expr 
            {
              Stmt RESULT =null;
		int lleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int lright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		LValue l = (LValue)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int eleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Expr e = (Expr)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		
        RESULT = new AssignStmt(l, e);
    
              CUP$parser$result = parser.getSymbolFactory().newSymbol("simple_stmt",8, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 40: // simple_stmt ::= call 
            {
              Stmt RESULT =null;
		int cleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int cright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		CallExpr c = (CallExpr)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		
        RESULT = new CallStmt(c);
    
              CUP$parser$result = parser.getSymbolFactory().newSymbol("simple_stmt",8, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 41: // call ::= T_ID T_LPAR T_RPAR 
            {
              CallExpr RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		
        RESULT = new CallExpr(id, new ArrayList<Expr>());
    
              CUP$parser$result = parser.getSymbolFactory().newSymbol("call",14, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 42: // call ::= T_ID T_LPAR expr_list T_RPAR 
            {
              CallExpr RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-3)).value;
		int argsleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int argsright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		ArrayList<Expr> args = (ArrayList<Expr>)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		
        RESULT = new CallExpr(id, args);
    
              CUP$parser$result = parser.getSymbolFactory().newSymbol("call",14, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 43: // expr_list ::= expr_list T_COMMA expr 
            {
              ArrayList<Expr> RESULT =null;
		int listleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int listright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		ArrayList<Expr> list = (ArrayList<Expr>)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int eleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Expr e = (Expr)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		
        list.add(e);
        RESULT = list;
    
              CUP$parser$result = parser.getSymbolFactory().newSymbol("expr_list",15, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 44: // expr_list ::= expr 
            {
              ArrayList<Expr> RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Expr e = (Expr)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		
        ArrayList<Expr> list = new ArrayList<Expr>();
        list.add(e);
        RESULT = list;
    
              CUP$parser$result = parser.getSymbolFactory().newSymbol("expr_list",15, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 45: // lvalue ::= T_ID 
            {
              LValue RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int idright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		
        RESULT = new VarLValue(id);
    
              CUP$parser$result = parser.getSymbolFactory().newSymbol("lvalue",13, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 46: // lvalue ::= lvalue T_LBRACKET expr T_RBRACKET 
            {
              LValue RESULT =null;
		int arrleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).left;
		int arrright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).right;
		LValue arr = (LValue)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-3)).value;
		int indexleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int indexright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		Expr index = (Expr)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		
        RESULT = new ArrayLValue(arr, index);
    
              CUP$parser$result = parser.getSymbolFactory().newSymbol("lvalue",13, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 47: // atom ::= T_NUM 
            {
              Expr RESULT =null;
		int nleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int nright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Integer n = (Integer)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		
        RESULT = new IntConst(n);
    
              CUP$parser$result = parser.getSymbolFactory().newSymbol("atom",12, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 48: // atom ::= T_STRING 
            {
              Expr RESULT =null;
		int sleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int sright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		String s = (String)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		
        RESULT = new StringConst(s);
    
              CUP$parser$result = parser.getSymbolFactory().newSymbol("atom",12, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 49: // atom ::= T_CHARCONST 
            {
              Expr RESULT =null;
		int cleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int cright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		String c = (String)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		
        RESULT = new CharConst(c);
    
              CUP$parser$result = parser.getSymbolFactory().newSymbol("atom",12, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 50: // atom ::= T_TRUE 
            {
              Expr RESULT =null;
		
        RESULT = new BoolConst(true);
    
              CUP$parser$result = parser.getSymbolFactory().newSymbol("atom",12, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 51: // atom ::= T_FALSE 
            {
              Expr RESULT =null;
		
        RESULT = new BoolConst(false);
    
              CUP$parser$result = parser.getSymbolFactory().newSymbol("atom",12, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 52: // atom ::= T_NIL 
            {
              Expr RESULT =null;
		
        RESULT = new NilConst();
    
              CUP$parser$result = parser.getSymbolFactory().newSymbol("atom",12, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 53: // atom ::= lvalue 
            {
              Expr RESULT =null;
		int lleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int lright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		LValue l = (LValue)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		
        RESULT = l;
    
              CUP$parser$result = parser.getSymbolFactory().newSymbol("atom",12, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 54: // atom ::= call 
            {
              Expr RESULT =null;
		int cleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int cright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		CallExpr c = (CallExpr)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		
        RESULT = c;
    
              CUP$parser$result = parser.getSymbolFactory().newSymbol("atom",12, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 55: // atom ::= T_LPAR expr T_RPAR 
            {
              Expr RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int eright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		Expr e = (Expr)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		
        RESULT = e;
    
              CUP$parser$result = parser.getSymbolFactory().newSymbol("atom",12, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 56: // atom ::= T_NEW type T_LBRACKET expr T_RBRACKET 
            {
              Expr RESULT =null;
		int tleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).left;
		int tright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).right;
		String t = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-3)).value;
		int eleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int eright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		Expr e = (Expr)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		
        RESULT = new NewArrayExpr(TypeConverter.fromString(t), e);
    
              CUP$parser$result = parser.getSymbolFactory().newSymbol("atom",12, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 57: // expr ::= atom 
            {
              Expr RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int aright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Expr a = (Expr)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		
        RESULT = a;
    
              CUP$parser$result = parser.getSymbolFactory().newSymbol("expr",11, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 58: // expr ::= T_MINUS expr 
            {
              Expr RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Expr e = (Expr)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		
        RESULT = new UnaryOp(UnaryOp.Operator.NEG, e);
    
              CUP$parser$result = parser.getSymbolFactory().newSymbol("expr",11, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 59: // expr ::= T_PLUS expr 
            {
              Expr RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Expr e = (Expr)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		
        RESULT = e;
    
              CUP$parser$result = parser.getSymbolFactory().newSymbol("expr",11, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 60: // expr ::= T_NOT expr 
            {
              Expr RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Expr e = (Expr)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		
        RESULT = new UnaryOp(UnaryOp.Operator.NOT, e);
    
              CUP$parser$result = parser.getSymbolFactory().newSymbol("expr",11, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 61: // expr ::= T_HEAD expr 
            {
              Expr RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Expr e = (Expr)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		
        RESULT = new UnaryOp(UnaryOp.Operator.HEAD, e);
    
              CUP$parser$result = parser.getSymbolFactory().newSymbol("expr",11, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 62: // expr ::= T_TAIL expr 
            {
              Expr RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Expr e = (Expr)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		
        RESULT = new UnaryOp(UnaryOp.Operator.TAIL, e);
    
              CUP$parser$result = parser.getSymbolFactory().newSymbol("expr",11, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 63: // expr ::= T_NILQ expr 
            {
              Expr RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Expr e = (Expr)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		
        RESULT = new UnaryOp(UnaryOp.Operator.NILQ, e);
    
              CUP$parser$result = parser.getSymbolFactory().newSymbol("expr",11, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 64: // expr ::= expr T_PLUS expr 
            {
              Expr RESULT =null;
		int lleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int lright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		Expr l = (Expr)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int rleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int rright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Expr r = (Expr)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		
        RESULT = new BinOp(BinOp.Operator.PLUS, l, r);
    
              CUP$parser$result = parser.getSymbolFactory().newSymbol("expr",11, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 65: // expr ::= expr T_MINUS expr 
            {
              Expr RESULT =null;
		int lleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int lright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		Expr l = (Expr)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int rleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int rright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Expr r = (Expr)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		
        RESULT = new BinOp(BinOp.Operator.MINUS, l, r);
    
              CUP$parser$result = parser.getSymbolFactory().newSymbol("expr",11, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 66: // expr ::= expr T_TIMES expr 
            {
              Expr RESULT =null;
		int lleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int lright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		Expr l = (Expr)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int rleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int rright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Expr r = (Expr)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		
        RESULT = new BinOp(BinOp.Operator.TIMES, l, r);
    
              CUP$parser$result = parser.getSymbolFactory().newSymbol("expr",11, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 67: // expr ::= expr T_DIV expr 
            {
              Expr RESULT =null;
		int lleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int lright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		Expr l = (Expr)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int rleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int rright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Expr r = (Expr)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		
        RESULT = new BinOp(BinOp.Operator.DIV, l, r);
    
              CUP$parser$result = parser.getSymbolFactory().newSymbol("expr",11, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 68: // expr ::= expr T_MOD expr 
            {
              Expr RESULT =null;
		int lleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int lright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		Expr l = (Expr)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int rleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int rright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Expr r = (Expr)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		
        RESULT = new BinOp(BinOp.Operator.MOD, l, r);
    
              CUP$parser$result = parser.getSymbolFactory().newSymbol("expr",11, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 69: // expr ::= expr T_EQ expr 
            {
              Expr RESULT =null;
		int lleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int lright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		Expr l = (Expr)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int rleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int rright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Expr r = (Expr)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		
        RESULT = new BinOp(BinOp.Operator.EQ, l, r);
    
              CUP$parser$result = parser.getSymbolFactory().newSymbol("expr",11, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 70: // expr ::= expr T_NEQ expr 
            {
              Expr RESULT =null;
		int lleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int lright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		Expr l = (Expr)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int rleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int rright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Expr r = (Expr)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		
        RESULT = new BinOp(BinOp.Operator.NEQ, l, r);
    
              CUP$parser$result = parser.getSymbolFactory().newSymbol("expr",11, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 71: // expr ::= expr T_LT expr 
            {
              Expr RESULT =null;
		int lleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int lright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		Expr l = (Expr)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int rleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int rright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Expr r = (Expr)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		
        RESULT = new BinOp(BinOp.Operator.LT, l, r);
    
              CUP$parser$result = parser.getSymbolFactory().newSymbol("expr",11, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 72: // expr ::= expr T_GT expr 
            {
              Expr RESULT =null;
		int lleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int lright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		Expr l = (Expr)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int rleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int rright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Expr r = (Expr)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		
        RESULT = new BinOp(BinOp.Operator.GT, l, r);
    
              CUP$parser$result = parser.getSymbolFactory().newSymbol("expr",11, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 73: // expr ::= expr T_LE expr 
            {
              Expr RESULT =null;
		int lleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int lright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		Expr l = (Expr)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int rleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int rright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Expr r = (Expr)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		
        RESULT = new BinOp(BinOp.Operator.LE, l, r);
    
              CUP$parser$result = parser.getSymbolFactory().newSymbol("expr",11, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 74: // expr ::= expr T_GE expr 
            {
              Expr RESULT =null;
		int lleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int lright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		Expr l = (Expr)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int rleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int rright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Expr r = (Expr)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		
        RESULT = new BinOp(BinOp.Operator.GE, l, r);
    
              CUP$parser$result = parser.getSymbolFactory().newSymbol("expr",11, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 75: // expr ::= expr T_AND expr 
            {
              Expr RESULT =null;
		int lleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int lright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		Expr l = (Expr)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int rleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int rright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Expr r = (Expr)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		
        RESULT = new BinOp(BinOp.Operator.AND, l, r);
    
              CUP$parser$result = parser.getSymbolFactory().newSymbol("expr",11, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 76: // expr ::= expr T_OR expr 
            {
              Expr RESULT =null;
		int lleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int lright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		Expr l = (Expr)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int rleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int rright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Expr r = (Expr)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		
        RESULT = new BinOp(BinOp.Operator.OR, l, r);
    
              CUP$parser$result = parser.getSymbolFactory().newSymbol("expr",11, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 77: // expr ::= expr T_HASH expr 
            {
              Expr RESULT =null;
		int lleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int lright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		Expr l = (Expr)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int rleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int rright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Expr r = (Expr)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		
        RESULT = new BinOp(BinOp.Operator.CONS, l, r);
    
              CUP$parser$result = parser.getSymbolFactory().newSymbol("expr",11, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number "+CUP$parser$act_num+"found in internal parse table");

        }
    } /* end of method */

  /** Method splitting the generated action code into several parts. */
  public final java_cup.runtime.Symbol CUP$parser$do_action(
    int                        CUP$parser$act_num,
    java_cup.runtime.lr_parser CUP$parser$parser,
    java.util.Stack            CUP$parser$stack,
    int                        CUP$parser$top)
    throws java.lang.Exception
    {
              return CUP$parser$do_action_part00000000(
                               CUP$parser$act_num,
                               CUP$parser$parser,
                               CUP$parser$stack,
                               CUP$parser$top);
    }
}

}
