
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int T_ELSE = 7;
  public static final int T_SKIP = 25;
  public static final int T_EQ = 40;
  public static final int UMINUS = 47;
  public static final int T_LIST = 16;
  public static final int T_FALSE = 11;
  public static final int T_CHARCONST = 50;
  public static final int T_LPAR = 28;
  public static final int T_INT = 15;
  public static final int T_FOR = 12;
  public static final int T_REF = 23;
  public static final int T_ASSIGN = 35;
  public static final int T_NILQ = 20;
  public static final int T_RETURN = 24;
  public static final int T_NOT = 21;
  public static final int T_AND = 2;
  public static final int T_NIL = 19;
  public static final int T_ELSIF = 8;
  public static final int T_DIV = 39;
  public static final int T_NUM = 51;
  public static final int T_GT = 43;
  public static final int T_CHAR = 4;
  public static final int T_RBRACKET = 31;
  public static final int EOF = 0;
  public static final int T_MINUS = 37;
  public static final int error = 1;
  public static final int T_HASH = 46;
  public static final int T_NEW = 18;
  public static final int T_GE = 45;
  public static final int T_MOD = 17;
  public static final int T_NEQ = 41;
  public static final int T_DECL = 5;
  public static final int T_COMMA = 32;
  public static final int T_STRING = 49;
  public static final int T_RPAR = 29;
  public static final int T_TAIL = 26;
  public static final int T_SEMICOLON = 33;
  public static final int T_BOOL = 3;
  public static final int T_PLUS = 36;
  public static final int T_EXIT = 10;
  public static final int T_LT = 42;
  public static final int T_OR = 22;
  public static final int T_END = 9;
  public static final int T_DEF = 6;
  public static final int T_TRUE = 27;
  public static final int T_TIMES = 38;
  public static final int T_IF = 14;
  public static final int T_ID = 48;
  public static final int T_COLON = 34;
  public static final int T_LE = 44;
  public static final int T_LBRACKET = 30;
  public static final int T_HEAD = 13;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "T_AND",
  "T_BOOL",
  "T_CHAR",
  "T_DECL",
  "T_DEF",
  "T_ELSE",
  "T_ELSIF",
  "T_END",
  "T_EXIT",
  "T_FALSE",
  "T_FOR",
  "T_HEAD",
  "T_IF",
  "T_INT",
  "T_LIST",
  "T_MOD",
  "T_NEW",
  "T_NIL",
  "T_NILQ",
  "T_NOT",
  "T_OR",
  "T_REF",
  "T_RETURN",
  "T_SKIP",
  "T_TAIL",
  "T_TRUE",
  "T_LPAR",
  "T_RPAR",
  "T_LBRACKET",
  "T_RBRACKET",
  "T_COMMA",
  "T_SEMICOLON",
  "T_COLON",
  "T_ASSIGN",
  "T_PLUS",
  "T_MINUS",
  "T_TIMES",
  "T_DIV",
  "T_EQ",
  "T_NEQ",
  "T_LT",
  "T_GT",
  "T_LE",
  "T_GE",
  "T_HASH",
  "UMINUS",
  "T_ID",
  "T_STRING",
  "T_CHARCONST",
  "T_NUM"
  };
}

